language: node_js
node_js:
  - "8"
before_script:
  - npm install
script:
  - npm run test
  - npm run build
deploy:
 provider: pages
 skip_cleanup: true
 local_dir: build
 github_token: $GITHUB_TOKEN
 on:
  branch: master
