export const SET_GISTS_SUCCESS = 'SET_GISTS_SUCCESS';
export const SET_GISTS_FAILURE = 'SET_GISTS_FAILURE';
export const SET_COMMENTS_SUCCESS = 'SET_COMMENTS_SUCCESS';
export const SET_COMMENTS_FAILURE = 'SET_COMMENTS_FAILURE';
export const SET_GIST_SUCCESS = 'SET_GIST_SUCCESS';
export const SET_GIST_FAILURE = 'SET_GIST_FAILURE';
export const FETCHING_GISTS = 'FETCHING_GISTS';
